try:
    a = int(input("Enter the no.:-"))
    print(a)

# Exception CRASH HOU DET NAHI
except Exception as a:
    print(a, "TRY AGAIN, This is wrong ")
    
else:
    print("This else statement are inside the else")
